### ISSUE TITLE
代码跑不起来

### ISSUE THREAD

**Issue by yly1994** [fandongmeng/DTMT_InDec#1]
如何快速发（shui）论文：

第一步、找到一个现有算法

第二步、加入一些新的层或超参数，并且想一个让它看上去有点道理的数学小解释

第三步、然后网（bao）格（li）搜索超参数，直到打败之前算法的基线模型

第四步、不要对用来比较的基线模型进行网格搜索

第五步、给这个方法想一个可爱的缩写（比如 koan，哈哈），然后放上基本上跑不起来 python2 代码到 github 去，并且在论文里留个链接

这样就水好一篇论文了！！！

19年的代码，还在用tensorflow 1.0 真的不是在水链接吗

**Comment by fandongmeng** [comment]
1. 我想你还是对这篇论文的思想有误解，如果有不明白的地方我可以进一步给你解答。
2. 关于跑起代码，你可以先确认下是不是遇到了缩进问题，以及你的计算环境是否OK。
3. 如果你还是无法跑起代码，可以与我联系遇到的问题细节，我可以帮你解决。
4. 这是18年的论文，只不过代码是后放出来的，用tensorflow 1.0没有什么问题，而且这也与学术研究无关，不应该用代码判断论文好坏。

**Comment by fandongmeng** [comment]
> 如何快速发（shui）论文：
> 
> 第一步、找到一个现有算法
> 
> 第二步、加入一些新的层或超参数，并且想一个让它看上去有点道理的数学小解释
> 
> 第三步、然后网（bao）格（li）搜索超参数，直到打败之前算法的基线模型
> 
> 第四步、不要对用来比较的基线模型进行网格搜索
> 
> 第五步、给这个方法想一个可爱的缩写（比如 koan，哈哈），然后放上基本上跑不起来 python2 代码到 github 去，并且在论文里留个链接
> 
> 这样就水好一篇论文了！！！
> 
> 19年的代码，还在用tensorflow 1.0 真的不是在水链接吗

1. 我想你还是对这篇论文的思想有误解，如果有不明白的地方我可以进一步给你解答。
2. 关于跑起代码，你可以先确认下是不是遇到了缩进问题，以及你的计算环境是否OK。
3. 如果你还是无法跑起代码，可以与我联系遇到的问题细节，我可以帮你解决。
4. 这是18年的论文，只不过代码是后放出来的，用的是tensorflow 1.10（更正一下），而且这也与学术研究无关，不应该用代码判断论文好坏。
